### ISSUE TITLE
vxuNonLinearFilter unimplemented from OpenVX Specification 1.1

### ISSUE THREAD

**Issue by sheldonrobinson** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#20]
The headers have been updated to  OpenVX 1.1 but the function vxuNonLinearFilter is unimplemented.

**Comment by gshisha** [comment]
We are not compliant with OpenVX 1.1 yet,and it is work in progress. As of now, we are still only OpenVX 1.0.1 compliant.
