### ISSUE TITLE
Error when building with OpenCL enabled

### ISSUE THREAD

**Issue by CACUser** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#22]
Hi - I am trying to build with OpenCL and am getting the following errors:
amdovx-core-master/openvx/ago/ago_util_opencl.cpp: In function ‘int agoGpuOclSetKernelArgs(cl_kernel, vx_uint32&, AgoData*, bool, vx_uint32, vx_uint32)’:
amdovx-core-master/openvx/ago/ago_util_opencl.cpp:697:9: error: ‘union cl_uint2’ has no member named ‘s0’
   value.s0 = data->u.thr.threshold_lower;
         ^
amdovx-core-master/openvx/ago/ago_util_opencl.cpp:700:10: error: ‘union cl_uint2’ has no member named ‘s1’
    value.s1 = data->u.thr.threshold_upper;
          ^
amdovx-core-master/openvx/ago/ago_util_opencl.cpp: In function ‘int agoGpuOclDataInputSync(_vx_graph*, cl_kernel, vx_uint32&, AgoData*, vx_uint32, vx_uint32, bool, bool, bool)’:
amdovx-core-master/openvx/ago/ago_util_opencl.cpp:931:9: error: ‘union cl_uint2’ has no member named ‘s0’
   value.s0 = data->u.thr.threshold_lower;
         ^
amdovx-core-master/openvx/ago/ago_util_opencl.cpp:934:10: error: ‘union cl_uint2’ has no member named ‘s1’
    value.s1 = data->u.thr.threshold_upper;
          ^

What am I doing wrong?
Thanks!

**Comment by rgiduthuri** [comment]
Hope you resolved this by now. 

This looks like it is related to OpenCL platform. See the below:
https://github.com/KhronosGroup/OpenCL-Headers/blob/master/opencl20/CL/cl_platform.h#L1007

Could you please provide some info about the platform that gave this error?

**Comment by rgiduthuri** [comment]
Closing this.. if the issue still persists, please re-open the issue.
