### ISSUE TITLE
ERROR: clEnqueueNDRangeKernel(supernode,1,*,{1167360,0,0},...) failed(-54) for com.amd.loomsl.half_scale_gaussian

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#27]
recreated from amdovx-modules 

the problem looks like the local_work_size is not set for clEnqueueNDRangeKernel
and the kernel request the size 
the docs says
The work-group size to be used for kernel can also be specified in the program source using the __attribute__((reqd_work_group_size(X, Y, Z)))qualifier. In this case the size of work group specified by local_work_size must match the value specified by the reqd_work_group_size __attribute__ qualifier.

https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html

@rgiduthuri so the local_work_size should be the same as the reqd_work_group_size from the kernel right?

**Comment by rgiduthuri** [comment]
Yes. When local_work_size is supplied it should match reqd_work_group_size from the kernel.
As per the below line in khronos specification, the OpenCL implementation will determine local_work_size from OpenCL program, which is reqd_work_group_size in this case:
- local_work_size can also be a NULL value in which case the OpenCL implementation will determine how to be break the global work-items into appropriate work-group instances.

Is it possible that the OpenCL implementation that you're using doesn't comply with this feature?

**Comment by arpu** [comment]
could it be this only work if the kernel does not use reqd_work_group_size

if  local_work_size  and kernel does not use reqd_work_group_size
if the kernel use reqd_work_group_size the local_work_size must be set

**Comment by rgiduthuri** [comment]
@arpu could you try the below change and confirm if works?
https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-core/pull/35

**Comment by arpu** [comment]
@rgiduthuri  yes  #35 fixes this
