### ISSUE TITLE
gdf Examples - display images is not supporting

### ISSUE THREAD

**Issue by peter73421** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#4]
I wanna run canny.gdf example and executing runvx.exe file canny.gdf I got:

c:\amdovx-core\build\runvx\Debug>runvx.exe -v file canny.gdf

****\* VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

OK: using AMD OpenVX 0.9.1
OK: enabled graph scheduling in separate threads

> > include canny.gdf
> > data input = image:640,480,RGB2
> > data output = image:640,480,U008
> > read input raja-koduri-640x480.jpg
> > view input inputWindow
> > ERROR: display of image type (   ☺) is not support. Exiting.

How to resolve it?
Thank you.

**Comment by xqch1983** [comment]
@peter73421  can you share canny.gdf to me, I have not found gdf files.

**Comment by gshisha** [comment]
Just checked and this works on my side. Issue might be with the OpenCV install on your system, which is used for input image decode and display. Can you do the following checks.
Verify if:
-> OpenCV 3.0 download is fine, OpenCV_DIR environment variable should point to OpenCV/build folder (check for these instructions/link in README.md file)
-> Try converting raja-koduri-640x480.jpg to raw rgb using some other tool, and send that as input image
