### ISSUE TITLE
ERROR This build doesn't support CAMERA option 

### ISSUE THREAD

**Issue by xqch1983** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#5]
when i run runvx.exe in command line, such as : runvx.exe file canny.gdf  

results is 
OK: suing AMD OpenVX 0.9.1
OK enable graph scheduling in separate threads
ERROR: This build does't support CAMERA option

can you share where to modify source file or setting to solve this issue?

 thanks.

**Comment by gshisha** [comment]
It looks like the build you have does not have OpenCV included. The runvx->CMakeLists.txt tries to find the OpenCV package on your system, and has the following lines:

if (OpenCV_FOUND)
	target_compile_definitions(runvx PUBLIC USE_OPENCV=1)
	include_directories(${OpenCV_INCLUDE_DIRS})
	target_link_libraries(runvx ${OpenCV_LIBRARIES})
else(OpenCV_FOUND)
	target_compile_definitions(runvx PUBLIC USE_OPENCV=0)
endif(OpenCV_FOUND)

The OpenCV package is needed for accessing the camera and display.
