### ISSUE TITLE
Merging of nodes

### ISSUE THREAD

**Issue by VishnuTejaM** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#6]
I'm going through the Graph Manager code. As far as my understanding, merging of functions are not yet supported. Am I right?
If so, are you planning to release any updated version?

**Comment by rgiduthuri** [comment]
They are supported. Let me know your use case, so that I can point you at the right file/function.

**Comment by VishnuTejaM** [comment]
Using sample gdf files, I'm just trying to understand different kinds of optimizations available.
In 'agoOptimizeDrama( )', the 'agoOptimizeDramaMerge( )' is always returning 'graphGotModified=0'.
So, I interpreted this as if Merging is not happening at this point. Is there any other file to go through?

**Comment by rgiduthuri** [comment]
Code needs some cleanup. Currently the merge happens inside agoOptimizeDramaRemove().

**Comment by VishnuTejaM** [comment]
Thank you. Will look into it.
