### ISSUE TITLE
OpenVX Neural Network Extension

### ISSUE THREAD

**Issue by bhack** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#7]
Do you have a roadmap to support [OpenVX Neural Network Extension](https://www.khronos.org/news/press/khronos-launches-dual-neural-network-standard-initiatives) here?

**Comment by rgiduthuri** [comment]
Can't discuss roadmap on this forum. Please send me an email.

**Comment by bhack** [comment]
Do you have a public one?
