### ISSUE TITLE
Inconsistent orders of params array?

### ISSUE THREAD

**Issue by thanhmvu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#71]
Hi,

It seems that all VX functions defined in **vx_nodes.cpp** have the params array ordered as `[input1,input2, ... inputK, output]`. For example, `vxAbsDiffNode()` has its `params[]` being `[in1, in2, out]`. However, in **ago_kernel_api.cpp**, functions such as `agoKernel_AbsDiff_U8_U8U8()` actually assume a reverted order, for instance `[oImg, iImg0, iImg1]`, which seems incorrect to me. Please let me know whether I missed something or there is an issue with this logic.

Thank you.

Best,
Thanh

**Comment by kiritigowda** [comment]
Hi @thanhmvu, the ago_kernel_api.cpp is the internal implementation of the kernels. As the OpenVX API allows a few of the inputs to be optional, representing this way gives us some leverage. As long as the difference in representation is understood between the calls, it is not a problem.
