### ISSUE TITLE
Camera setup on GDF file

### ISSUE THREAD

**Issue by bnascimento** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#8]
How can I setup a GDF file to work with the camera as an input?
Anyone has a good idea?
Cheers

**Comment by gshisha** [comment]
Try with following line in the gdf:
data input = image:640,480,RGB2:CAMERA,0:view,SEE-CAMERA

This has dependency on OpenCV.

**Comment by bnascimento** [comment]
That helped, thank you very much
